import { Roboto } from "next/font/google";
import "./globals.css";

import { Provider } from "@/provider/Provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          <main className="w-full h-full bg-background">{children}</main>
        </Provider>
      </body>
    </html>
  );
}